# Generated by Django 4.2.2 on 2023-06-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_clients_company_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.products'),
        ),
    ]
