# Generated by Django 4.2.2 on 2023-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_company_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(to='app1.products'),
        ),
    ]
