# Generated by Django 4.2.2 on 2023-06-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_company_products_company_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.AddField(
            model_name='clients',
            name='compani',
            field=models.ManyToManyField(to='app1.company'),
        ),
        migrations.AddField(
            model_name='clients',
            name='products',
            field=models.ManyToManyField(to='app1.products'),
        ),
        migrations.AddField(
            model_name='clients',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='app1.company'),
        ),
    ]
