# Generated by Django 4.2.2 on 2023-06-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_clients_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='compani',
            new_name='company',
        ),
    ]
