# Generated by Django 4.2.2 on 2023-06-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_compani_clients_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
