# Generated by Django 4.2.2 on 2023-06-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_clients_company_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='products',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='worker',
        ),
        migrations.AddField(
            model_name='products',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_products', models.IntegerField(default=0)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.clients')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.worker')),
            ],
        ),
    ]
