# Generated by Django 4.2.2 on 2023-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_clients_products_remove_clients_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost_of_storing_1_product_during_the_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='demand_last_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='demand_per_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='demand_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price_of_1_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='restocking_time',
            field=models.IntegerField(default=0),
        ),
    ]
