# Generated by Django 4.2.2 on 2023-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_products_cost_of_storing_1_product_during_the_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost_of_storing_1_product_during_the_year',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
