# Generated by Django 4.2.2 on 2023-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_products_cost_of_storing_1_product_during_the_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
